baseURL = "https://www.senergygroup.org/"
languageCode = "en-us"
title = "Senergy Group"
googleAnalytics = ""
#enableRobotsTXT = true

disableKinds = ["term"]

[params]
snipcart_key = "MmM3NzNiYjMtYzU3MS00ZmY3LTkzYTEtYzJiYWE5ZmI4YTlhNjM4MjY0MjAwNTExNTgwMjMy"

[params.author]
name = "Senergy Group"
email = "contact.senergy.group@gmail.com"
twitter = "fur" # twitter username without the @ symbol
phone = ""

[params.social]
name = "Fur Template"
links = [
	"https://github.com/CloudCannon/fur-hugo-template"
]

[_select_data]
garment_type = ["hat", "top"]

[cloudcannon._options.type]
hidden = true

[cloudcannon._comments]
map = "Update the map location and display settings."
latitude = "Coordinates for the center marker on the map."
longitude = "Coordinates for the center marker on the map."
zoom = "The zoom level for the map."
pricing_table = "Update the information in the pricing tables."
highlight = "Emphasis the text"
color = "The background color used in the plan name and call to action."
new_window = "Open link in new window"
description = "This is used for facebook shares of the page and google indexing"

[cloudcannon.collections.products]
_enabled_editors = ["data"]
_icon = "shopping_cart"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true